name: Vercel Production Deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global next@latest
      - name: Install Vercel CLI
        run: npm install
      - name: Build Project Artifacts
        run: npx next build
      - name: Push
        uses: nicholasgriffintn/github-branch-deployment-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
          BRANCH: website
          FOLDER: out
          MESSAGE: 'Build: ({sha}) {msg}'
